@startmindmap
* Tělo dokumentu
** Dříve vyslovená přání
** Urgentní informace
** Údaje o hospitalizaci
** Důvod přijetí
** Stav při přijetí 
** Anamnéza pacienta
** Průběh hospitalizace
** Stav při propuštění
** Doporučení
@endmindmap