@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "FunctionalStatus" <<LogicalModel>> [[StructureDefinition-FunctionalStatusCz.html]]
note top #PaleTurquoise [[ConceptMap-hospitalStay2FHIR-cz-hdr.html]]
Concept Map
endnote
class "composition-cz-hdr" <<Profile>> [[StructureDefinition-cz-composition-hdr.html]]
"FunctionalStatus" <|. "composition-cz-hdr"
class "ClinicalImpression" <<Profile>> [[http://hl7.org/fhir/StructureDefinition/ClinicalImpression]]
"FunctionalStatus" <|. "ClinicalImpression"
"composition-cz-hdr" -d[hidden]-> "ClinicalImpression"
class "Condition-cz" <<Profile>> [[StructureDefinition-cz-condition-hdr.html]]
"FunctionalStatus" <|. "Condition-cz"
"ClinicalImpression" -d[hidden]-> "Condition-cz"
@enduml
