@startmindmap
* header
** Identification of the patient/subject
** Patient/subject related contact information
** Health insurance and payment information
** Information recipient
** Author
** Attester
** Legal authenticator
** Document metadata
@endmindmap