@startmindmap
* Hlavička dokumentu
** Identifikace pacienta
** Kontaktní informace pacienta
** Zdravotní pojištění
** Příjemce dokumentu
** Autor
** Ověřil
** Zodpovídá
** Metadata dokumentu
@endmindmap