@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "HospitalDischargeReport" <<LogicalModel>> [[StructureDefinition-HospitalDischargeReportCz.html]]
note top #PaleTurquoise [[ConceptMap-hdr2FHIR-cz-hdr.html]]
Concept Map
endnote
class "bundle-cz-hdr" <<Profile>> [[StructureDefinition-cz-bundle-hdr.html]]
"HospitalDischargeReport" <|. "bundle-cz-hdr"
class "composition-cz-hdr" <<Profile>> [[StructureDefinition-cz-composition-hdr.html]]
"HospitalDischargeReport" <|. "composition-cz-hdr"
"bundle-cz-hdr" -d[hidden]-> "composition-cz-hdr"
@enduml
